
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: topg-server
    restart: unless-stopped
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=utility,compute
    networks:
      - topg-network

  webui:
    build: 
      context: ./webui
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    container_name: topg-webui
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - topg-network

networks:
  topg-network:
    driver: bridge
