name: Build Server

on:
  push:
    paths:
      - 'server/**'
    branches:
      - main
      - develop
  pull_request:
    paths:
      - 'server/**'

jobs:
  build:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone vcpkg
        working-directory: server
        run: git clone https://github.com/microsoft/vcpkg.git

      - name: Setup vcpkg
        working-directory: server
        run: ./vcpkg/bootstrap-vcpkg.sh

      - name: Configure CMake
        working-directory: server
        run: cmake . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        working-directory: server
        run: cmake --build build --config Release

      - name: Prepare artifacts
        working-directory: server
        run: |
          mkdir -p artifacts
          cp build/topg artifacts/
          chmod +x artifacts/topg
          tar -czf topg-linux-x64.tar.gz -C artifacts topg

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: topg-linux
          path: server/topg-linux-x64.tar.gz
          retention-days: 30

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: Generate release tag
        id: tag
        run: |
          TAG="server-v$(date +'%Y.%m.%d-%H%M%S')"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Server Build ${{ steps.tag.outputs.date }}
          body: |
            Automated server build from commit ${{ github.sha }}

            ## Changes
            ${{ github.event.head_commit.message }}

            ## Downloads
            - **Linux**: topg-linux-x64.tar.gz
          files: |
            release-artifacts/topg-linux/*.tar.gz
          draft: false
          prerelease: false
